#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

# shellcheck source=tools/scripts/ports.sh
source tools/scripts/ports.sh
# shellcheck source=tools/scripts/state.sh
source tools/scripts/state.sh
# shellcheck source=tools/scripts/compose.sh
source tools/scripts/compose.sh

ensure_state_dir

POSTGRES_PORT="${POSTGRES_PORT:-5433}"
REDIS_PORT="${REDIS_PORT:-6379}"

if is_tcp_port_listening "127.0.0.1" "$POSTGRES_PORT"; then
  POSTGRES_PORT="$(pick_free_port 5433)"
fi
if is_tcp_port_listening "127.0.0.1" "$REDIS_PORT"; then
  REDIS_PORT="$(pick_free_port 6379)"
fi

export POSTGRES_PORT REDIS_PORT

INFRA_ENV_FILE="$(infra_env_path)"
{
  echo "# Generated by tools/scripts/infra-up.sh"
  echo "export POSTGRES_PORT=${POSTGRES_PORT}"
  echo "export REDIS_PORT=${REDIS_PORT}"
} > "$INFRA_ENV_FILE"

local_compose_file="$(compose_file)"
compose_env_path=""
if compose_env_path="$(compose_env_file)"; then
  :
fi

echo "infra-up: postgres_port=${POSTGRES_PORT} redis_port=${REDIS_PORT}"
echo "infra-up: compose_file=${local_compose_file}"
if [[ -n "${compose_env_path}" ]]; then
  echo "infra-up: compose_env_file=${compose_env_path}"
else
  echo "infra-up: compose_env_file=<none>"
fi
echo "infra-up: wrote $(realpath "$INFRA_ENV_FILE")"

max_attempts="${INFRA_UP_MAX_ATTEMPTS:-3}"
if [[ ! "${max_attempts}" =~ ^[0-9]+$ || "${max_attempts}" -lt 1 ]]; then
  max_attempts=3
fi

attempt=1
while [[ "${attempt}" -le "${max_attempts}" ]]; do
  if compose_cmd "$local_compose_file" up -d --wait; then
    echo "infra-up: OK (attempt ${attempt}/${max_attempts})"
    exit 0
  fi

  if [[ "${attempt}" -eq "${max_attempts}" ]]; then
    echo "infra-up: FAIL after ${max_attempts} attempt(s)" >&2
    exit 1
  fi

  sleep_s=$((attempt * 2))
  echo "infra-up: retrying in ${sleep_s}s (attempt ${attempt}/${max_attempts})..." >&2
  sleep "${sleep_s}"
  attempt=$((attempt + 1))
done
