#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

# shellcheck source=tools/scripts/ports.sh
source tools/scripts/ports.sh
# shellcheck source=tools/scripts/state.sh
source tools/scripts/state.sh
# shellcheck source=tools/scripts/compose.sh
source tools/scripts/compose.sh

ensure_state_dir

POSTGRES_PORT="${POSTGRES_PORT:-5433}"
REDIS_PORT="${REDIS_PORT:-6379}"

if is_tcp_port_listening "127.0.0.1" "$POSTGRES_PORT"; then
  POSTGRES_PORT="$(pick_free_port 5433)"
fi
if is_tcp_port_listening "127.0.0.1" "$REDIS_PORT"; then
  REDIS_PORT="$(pick_free_port 6379)"
fi

export POSTGRES_PORT REDIS_PORT

INFRA_ENV_FILE="$(infra_env_path)"
{
  echo "# Generated by tools/scripts/infra-up.sh"
  echo "export POSTGRES_PORT=${POSTGRES_PORT}"
  echo "export REDIS_PORT=${REDIS_PORT}"
} > "$INFRA_ENV_FILE"

local_compose_file="$(compose_file)"

echo "infra-up: postgres_port=${POSTGRES_PORT} redis_port=${REDIS_PORT}"
echo "infra-up: compose_file=${local_compose_file}"
echo "infra-up: wrote $(realpath "$INFRA_ENV_FILE")"

docker compose -f "$local_compose_file" up -d --wait
